blog/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from polls.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('polls.urls',namespace="index") ),
    path('index', include('polls.urls',namespace="index")),    
    path('post/<slug:slug>', include('polls.urls',namespace="post")) ,
    path('about/<slug:slug>', include('polls.urls',namespace="about")),
    path('contact', include('polls.urls',namespace="contact")),
    #path('tinymce/', include('tinymce.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    

]

polls/urls.py
from django.urls import path, re_path

from . import views
app_name = 'polls'



urlpatterns = [
   
    path('', views.index, name='index'),   
    path('index', views.index, name='index'),
    path('post/<slug:slug>', views.post, name='post'),
    path('contact', views.contact, name='contact'),
    path('<slug:slug>', views.about, name='about'),
       
]

polls/models.py
from django.db import models
#from tinymce.models import HTMLField
from ckeditor_uploader.fields import RichTextUploadingField

class Pages(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)    
    page = models.CharField(max_length=250, verbose_name='Səhifənin adı')    
    page_url = models.CharField(max_length=250, verbose_name='Alt səhifə (url)')    
    

    def __str__(self):
        return self.page

class Post(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)  
    page_id = models.ForeignKey(Pages, on_delete=models.CASCADE)  
    title = models.CharField(max_length=250, verbose_name='Başlıq')
    slug = models.SlugField(max_length=250,verbose_name='Slug')
    picture = models.ImageField(upload_to='img/',blank=True,verbose_name='Şəkil')
    created_at = models.DateTimeField(verbose_name='İndiki vaxt')
    content = RichTextUploadingField() #HTMLField()
    def __str__(self):
        return self.title

    def image_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="%s" width="100px" height="100px" />'%(self.picture.url))
    image_tag.short_description = 'Image'





    






    """class About(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)    
    title = models.CharField(max_length=250, verbose_name='Başlıq')    
    picture = models.ImageField(upload_to='img/',blank=True,verbose_name='Şəkil')    
    content = RichTextUploadingField() #HTMLField()

    def __str__(self):
        return self.title
    
    def image_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="%s" width="100px" height="100px" />'%(self.picture.url))
    image_tag.short_description = 'Image'


class Contact(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)    
    title = models.CharField(max_length=250, verbose_name='Başlıq')    
    picture = models.ImageField(upload_to='img/',blank=True,verbose_name='Şəkil')    
    content = RichTextUploadingField() #HTMLField()

    def __str__(self):
        return self.title
    
    def image_tag(self):
        from django.utils.html import mark_safe
        return mark_safe('<img src="%s" width="100px" height="100px" />'%(self.picture.url))
    image_tag.short_description = 'Image'"""

polls/views.py
from django.shortcuts import render,get_object_or_404
from .models import *
from django.core.paginator import Paginator


def index(request):
    pages= Pages.objects.all()    
    data = Post.objects.select_related("page_id").filter(page_id_id__page_url="index")    
    data2 = Post.objects.order_by("slug")        
    page = Paginator(data2, 1)
    page_number = request.GET.get('page')
    page_obj = page.get_page(page_number)
    print("$$$$$",pages)
    return render(request,"main.html",{"data":data,"page_obj":page_obj,"pages":pages})


def post(request,slug=None):
    pages= Pages.objects.all()
    data = get_object_or_404(Post.objects.filter(slug__contains=slug).values())
    data2 = Post.objects.select_related("page_id").filter(page_id_id__page_url="index")[::-3]
    print(data,"data2$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$4")
    return render(request,"post.html",{"data":data,"data2":data2,"pages":pages})




def about(request,slug=None):    
    data = get_object_or_404(Post.objects.select_related("page_id").filter(page_id_id__page_url=slug))    
    print(data,"data")
    pages= Pages.objects.all()
    return render(request,"about.html",{"data":data,"pages":pages})

def contact(request):
    pages= Pages.objects.all()
    data = Post.objects.select_related("page_id").filter(page_id_id__page_url="contact").values()
    print("data",data[0]['picture'])
    return render(request,"contact.html",{"data":data[0],"pages":pages})

templates/about.html
{% extends "header.html" %}
{% load static %}
{% block body %}
{% include 'nav.html' with url=pages%}
    <main>
      <div class="container">
        <div class="col-md-12">
          <div class="blog-post  blog-post--fullwidth  blog-post--page">
            <div class="blog-post__image">
              <img src="../static/{{ data.picture }}" alt="About Me">
            </div>
            <div class="blog-post-wrapper">
              <div class="blog-post__title">
                <h1>{{data.title}}</h1>
              </div>
              <div class="blog-post__content">
                {{data.content|safe}}
                </div>
              <div class="blog-post__footer">
                <div class="blog-post__footer-social">
                  <span>Share:</span>
                  <div class="blog-post__footer-social-icons">
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    {% include 'footer.html' %}
    {%endblock%}

templates/contact.html
{% extends "header.html" %}
{% load static %}
{% block body %}
{% include 'nav.html' with url=pages%}

    <main>
      <div class="container">
        <div class="col-md-12  col-lg-12">
          <div class="blog-post  blog-post--fullwidth  blog-post--page">
            <div class="blog-post__image">
              <img src="{% static data.picture %}" alt="Contact">
            </div>
            <div class="blog-post-wrapper">
              <div class="blog-post__title">
                <h1>{{data.title}}</h1>
              </div>
              <div class="blog-post__content">
                {{data.content|safe}}
              </div>
              <div class="blog-post__contact">
                <form action="php/contact-form-handler.php" method="post">
                  <p class="blog-post__contact-author">
                    <label for="contact-author">Name*</label>
                    <input id="contact-author" type="text" name="contact-author" size="30" aria-required="true" required>
                  </p>
                  <p class="blog-post__contact-email">
                    <label for="contact-email">Email*</label>
                    <input id="contact-email" type="email" name="contact-email" size="30" aria-required="true" required>
                  </p>
                  <p class="blog-post__contact-message">
                    <label for="contact-message">Message</label>
                    <textarea id="contact-message" name="contact-message" cols="45" aria-required="true"></textarea>
                  </p>
                  <p class="blog-post__contact-submit">
                    <input id="contact-submit" type="submit" name="contact-submit" size="30" value="Send">
                  </p>
                </form>
              </div>
              <div class="blog-post__footer">
                <div class="blog-post__footer-social">
                  <span>Share:</span>
                  <div class="blog-post__footer-social-icons">
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    {% include 'footer.html' %}
    {%endblock%}

templates/footer.html
<footer class="page-footer">
    <div class="container  page-footer__top">
      <div class="col-sm-6  col-md-6">
        <div class="page-footer__top-about">
          <h4>Murad Əlİyev</h4>
          <p>Əxlaqı tərbiyə edən ən nadir kitab – vicdandır. Onunla tez – tez məsləhətləşmək lazımdır.
          </p>
          <p>Phone: +994558984826</p>
          <p>Email: <a href="mailto:murad.aliyev.tqo15@gmail.com">murad.aliyev.tqo15@gmail.com</a></p>
        </div>
      </div>
      
      
    </div>
    <div class="container  page-footer__bottom">
      <div class="col-sm-8  col-md-8  page-footer__bottom-copyright">
        <p>2020 © Murad. Personal Blog.</p>
      </div>
     
    </div>
  </footer>
  <div class="search-popup">
    <svg class="search-popup__close">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-close"></use>
    </svg>
    <div class="search-popup__container  container">
      <form action="index.html">
        <input type="text" size="32" placeholder="Search">
      </form>
    </div>
  </div>
  <div class="content-overlay"></div>

templates/index.html
<section class="container  top-slider">
  <div class="col-md-12">
    <div class="bxslider">
      {% for d in data %}
      <div>
        <div class="featured-image" style="background-image:url(static/{{ d.picture }});">
          <div class="featured-image__bg"></div>
          <div class="featured-image__content">
            <span class="featured-image__content-category">
              <a href="#">Lifestyle</a>
            </span>
            <span class="featured-image__content-title">
              <a href="{% url 'polls:post' slug=d.slug %}">{{d.title}}</a>
            </span>
            <p>{{d.content|truncatewords_html:20|safe}}</p>
            <span class="featured-image__content-link">
              <a href="{% url 'polls:post' slug=d.slug %}">Read More</a>
            </span>
          </div> 
        </div>
      </div>{%endfor%}
    </div>
  </div>
</section>

    <main>
      <div class="container">
        <div class="col-md-12  container--grid">  
            

          <div class="row">  
            {% for d in data %}         
            <div class="col-sm-6  col-md-6  blog-post  blog-post--grid">
              <div class="blog-post-wrapper">
                <div class="blog-post__info  blog-post__info--top">
                  
                </div>
                <div class="blog-post__title">
                  <h2><a href="{% url 'polls:post' slug=d.slug %}">{{d.title|truncatechars:30}}</a></h2>
                </div>
                <div class="blog-post__info">
                  
                  <span>{{d.created_at}}</span>
                  
                </div>
              </div>
              <div class="blog-post__image">
                <a href="{% url 'polls:post' slug=d.slug %}" ><img style="width:525px;height:350px" src="static/{{ d.picture }}" alt="{{d.title}}"></a>
              </div>
              <div class="blog-post-wrapper">
                <div class="blog-post__content">
                  
                  <p>{{d.content|truncatewords_html:5|safe}}</p>
                </div>
                <div class="blog-post__footer">
                  <a class="blog-post__footer-link" href="{% url 'polls:post' slug=d.slug %}">Read more</a>
                </div>
              </div>
            </div>{%endfor%}
          </div>
          
          <nav class="blog-pagination">
            <ul class="blog-pagination__items">
               
              {% if page_obj.has_previous %}
              <li class="blog-pagination__item  blog-pagination__item--active">
                <a href="?page=1">1</a>
              </li> 
              <li class="blog-pagination__item">
                <a href="?page={{ page_obj.previous_page_number }}"> previous</a>
              </li>
              
              {% endif %}
              <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>


              {% if page_obj.has_next %}
              
              <li class="blog-pagination__item">
                <a href="?page={{ page_obj.next_page_number }}">Next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </main>

    

templates/nav.html
<svg class="display-none">
    <symbol viewBox="0 0 512 512" id="icon-search">
      <path d="M448.3,424.7L335,311.3c20.8-26,33.3-59.1,33.3-95.1c0-84.1-68.1-152.2-152-152.2c-84,0-152,68.2-152,152.2
  s68.1,152.2,152,152.2c36.2,0,69.4-12.7,95.5-33.8L425,448L448.3,424.7z M120.1,312.6c-25.7-25.7-39.8-59.9-39.8-96.3
  s14.2-70.6,39.8-96.3S180,80,216.3,80c36.3,0,70.5,14.2,96.2,39.9s39.8,59.9,39.8,96.3s-14.2,70.6-39.8,96.3
  c-25.7,25.7-59.9,39.9-96.2,39.9C180,352.5,145.8,338.3,120.1,312.6z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-close">
      <polygon class="st0" points="340.2,160 255.8,244.3 171.8,160.4 160,172.2 244,256 160,339.9 171.8,351.6 255.8,267.8 340.2,352 
  352,340.3 267.6,256 352,171.8 "/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-facebook">
      <path d="M288,192v-38.1c0-17.2,3.8-25.9,30.5-25.9H352V64h-55.9c-68.5,0-91.1,31.4-91.1,85.3V192h-45v64h45v192h83V256h56.4l7.6-64
  H288z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-twitter">
      <path d="M492,109.5c-17.4,7.7-36,12.9-55.6,15.3c20-12,35.4-31,42.6-53.6c-18.7,11.1-39.4,19.2-61.5,23.5
  C399.8,75.8,374.6,64,346.8,64c-53.5,0-96.8,43.4-96.8,96.9c0,7.6,0.8,15,2.5,22.1c-80.5-4-151.9-42.6-199.6-101.3
  c-8.3,14.3-13.1,31-13.1,48.7c0,33.6,17.2,63.3,43.2,80.7C67,210.7,52,206.3,39,199c0,0.4,0,0.8,0,1.2c0,47,33.4,86.1,77.7,95
  c-8.1,2.2-16.7,3.4-25.5,3.4c-6.2,0-12.3-0.6-18.2-1.8c12.3,38.5,48.1,66.5,90.5,67.3c-33.1,26-74.9,41.5-120.3,41.5
  c-7.8,0-15.5-0.5-23.1-1.4C62.8,432,113.7,448,168.3,448C346.6,448,444,300.3,444,172.2c0-4.2-0.1-8.4-0.3-12.5
  C462.6,146,479,129,492,109.5z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-google">
      <path d="M242.1,275.6l-18.2-13.7l-0.1-0.1c-5.8-4.6-10-8.3-10-14.7c0-7,5-11.8,10.9-17.4l0.5-0.4c20-15.2,44.7-34.3,44.7-74.6
      c0-26.9-11.9-44.7-23.3-57.7h13L320,64H186.5c-25.3,0-62.7,3.2-94.6,28.6l-0.1,0.3C70,110.9,57,137.4,57,163.5
      c0,21.2,8.7,42.2,23.9,57.4c21.4,21.6,48.3,26.1,67.1,26.1c1.5,0,3,0,4.5-0.1c-0.8,3-1.2,6.3-1.2,10.3c0,10.9,3.6,19.3,8.1,26.2
      c-24,1.9-58.1,6.5-84.9,22.3C35.1,328.4,32,361.7,32,371.3c0,38.2,35.7,76.8,115.5,76.8c91.6,0,139.5-49.8,139.5-99
      C287,312,264.2,293.5,242.1,275.6z M116.7,139.9c0-13.4,3-23.5,9.3-30.9c6.5-7.9,18.2-13.1,29-13.1c19.9,0,32.9,15,40.4,27.6
      c9.2,15.5,14.9,36.1,14.9,53.6c0,4.9,0,20-10.2,29.8c-7,6.7-18.7,11.4-28.6,11.4c-20.5,0-33.5-14.7-40.7-27
      C120.4,173.5,116.7,153.1,116.7,139.9z M237.8,368c0,27.4-25.2,44.5-65.8,44.5c-48.1,0-80.3-20.6-80.3-51.3
      c0-26.1,21.5-36.8,37.8-42.5c18.9-6.1,44.3-7.3,50.1-7.3c3.9,0,6.1,0,8.7,0.2C224.9,336.8,237.8,347.7,237.8,368z"/>
      <polygon points="402,142 402,64 368,64 368,142 288,142 288,176 368,176 368,257 402,257 402,176 480,176 480,142 	"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-pinterest">
      <path d="M256,32C132.3,32,32,132.3,32,256c0,91.7,55.2,170.5,134.1,205.2c-0.6-15.6-0.1-34.4,3.9-51.4
      c4.3-18.2,28.8-122.1,28.8-122.1s-7.2-14.3-7.2-35.4c0-33.2,19.2-58,43.2-58c20.4,0,30.2,15.3,30.2,33.6
      c0,20.5-13.1,51.1-19.8,79.5c-5.6,23.8,11.9,43.1,35.4,43.1c42.4,0,71-54.5,71-119.1c0-49.1-33.1-85.8-93.2-85.8
      c-67.9,0-110.3,50.7-110.3,107.3c0,19.5,5.8,33.3,14.8,43.9c4.1,4.9,4.7,6.9,3.2,12.5c-1.1,4.1-3.5,14-4.6,18
      c-1.5,5.7-6.1,7.7-11.2,5.6c-31.3-12.8-45.9-47-45.9-85.6c0-63.6,53.7-139.9,160.1-139.9c85.5,0,141.8,61.9,141.8,128.3
      c0,87.9-48.9,153.5-120.9,153.5c-24.2,0-46.9-13.1-54.7-27.9c0,0-13,51.6-15.8,61.6c-4.7,17.3-14,34.5-22.5,48
      c20.1,5.9,41.4,9.2,63.5,9.2c123.7,0,224-100.3,224-224C480,132.3,379.7,32,256,32z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-instagram">
      <path d="M448.5,112c0-26.233-21.267-47.5-47.5-47.5H112c-26.233,0-47.5,21.267-47.5,47.5v289
  c0,26.233,21.267,47.5,47.5,47.5h289c26.233,0,47.5-21.267,47.5-47.5V112z M257,175.833c44.182,0,80,35.816,80,80s-35.818,80-80,80
  s-80-35.816-80-80S212.818,175.833,257,175.833z M416.5,160.5c0,8.836-7.163,16-16,16h-48c-8.837,0-16-7.164-16-16v-48
  c0-8.836,7.163-16,16-16h48c8.837,0,16,7.164,16,16V160.5z M401.5,416.5h-288c-8.822,0-17-8.178-17-17v-175h53.072
  c-3.008,10-4.572,20.647-4.572,31.583C145,286,156.65,314,177.805,335.154s49.279,32.741,79.195,32.741s58.041-11.681,79.195-32.835
  S369,286.016,369,256.099c0-10.936-1.563-21.599-4.572-31.599H416.5v175C416.5,408.322,410.322,416.5,401.5,416.5z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-flickr">
      <path d="M405.207,41H105.801C70.007,41,41,70.01,41,105.81v299.394C41,440.989,70.007,470,105.801,470h299.406
    C440.992,470,470,440.989,470,405.204V105.81C470,70.01,440.992,41,405.207,41z M166.039,324.698
    c-37.813,0-68.47-31.011-68.47-69.205c0-38.196,30.657-69.197,68.47-69.197c37.812,0,68.471,31.001,68.471,69.197
    C234.51,293.688,203.851,324.698,166.039,324.698z M344.977,324.698c-37.822,0-68.461-31.011-68.461-69.205
    c0-38.196,30.639-69.197,68.461-69.197s68.5,31.001,68.5,69.197C413.477,293.688,382.799,324.698,344.977,324.698z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-youtube">
      <path d="M481.554,99.554c-10.341-9.387-23.438-15.543-37.759-17.126c-31.132-3.484-62.545-5.239-94.063-6.118
    c-31.314-0.874-62.765-0.874-94.145-0.854c-31.374-0.019-62.821-0.019-94.141,0.854c-31.521,0.879-62.944,2.634-94.093,6.118
    c-14.308,1.583-27.398,7.743-37.729,17.133c-10.266,9.331-17.809,21.863-21.109,36.267c-4.453,19.309-6.707,39.455-7.845,59.727
    C-0.472,215.912-0.5,236.011-0.5,255.524c0,19.486,0,39.557,1.115,59.927c1.11,20.263,3.337,40.406,7.794,59.721
    c3.319,14.41,10.864,26.945,21.13,36.274c10.325,9.388,23.402,15.543,37.708,17.125c31.151,3.485,62.574,5.238,94.097,6.117
    c31.318,0.874,62.766,0.874,94.146,0.855c31.394,0.019,62.84,0.019,94.155-0.855c31.515-0.879,62.93-2.634,94.078-6.117
    c14.303-1.582,27.378-7.737,37.706-17.118c10.271-9.332,17.827-21.867,21.167-36.281c4.437-19.313,6.662-39.458,7.777-59.72
    c1.1-19.98,1.109-40.25,1.107-59.928h0.02v-0.989h-0.02c0.002-39.097,0.002-80.508-8.776-118.706
    C499.385,121.417,491.831,108.884,481.554,99.554L481.554,99.554z M185.416,333.265V167.563v-8.963l7.957,4.156
    c24.104,12.584,48.139,25.126,72.193,37.678c28.938,15.101,57.913,30.22,87.082,45.453l9.249,4.831l-9.269,4.808l-79.639,41.297
    c-26.508,13.742-53.016,27.482-79.638,41.273l-7.936,4.111L185.416,333.265L185.416,333.265z"/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-toggle">
      <g>
        <rect x="96" y="241" width="320" height="32"/>
        <rect x="96" y="145" width="320" height="32"/>
        <rect x="96" y="337" width="320" height="32"/>
      </g>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-arrow-right">
      <rect x="0" y="0" width="512" height="512" fill="#ffffff"/>
      <polygon points="160,115.4 180.7,96 352,256 180.7,416 160,396.7 310.5,256 "/>
    </symbol>
    <symbol viewBox="0 0 512 512" id="icon-arrow-left">
      <rect x="0" y="0" width="512" height="512" fill="#ffffff"/>
      <polygon points="352,115.4 331.3,96 160,256 331.3,416 352,396.7 201.5,256 "/>
    </symbol>
  </svg>
 
 


<header class="header  container">
    <div class="row  header__logo">
      <div class="col-md-3">
        <div class="social-icons">
          <a href="#">
            <svg>
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
            </svg>
          </a>
          <a href="#">
            <svg>
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
            </svg>
          </a>
          <a href="#">
            <svg>
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-instagram"></use>
            </svg>
          </a>
        </div>
      </div>
      <div class="col-md-6  logo">
        <h1><a class="logo__link" href="{% url 'polls:index' %}">Murad.</a></h1>
        <div class="logo__description">Personal Blog Template</div>
      </div>
      <div class="col-md-3  header__right">
        <div class="top-icons">
          <div class="top-icons__search">
            <svg>
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-search"></use>
            </svg>
          </div>
        </div>
      </div>
    </div>

<nav class="nav">
    <ul class="nav__list">
      {% for page in pages %}
      <li class="nav__item">
        
        <a href="{% url 'polls:about'  slug=page.page_url%}">{{page}}</a>
        
      </li>
              {%endfor%}
      
    </ul>
  </nav>
 
      <div class="nav-toggle">
        <svg class="nav-toggle__icon">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-toggle"></use>
        </svg>
      </div>
    </header>

templates/post.html
{% extends "header.html" %}
{% load static %}
{% block body %}
{% include 'nav.html' with url=pages%}

    <main>
      <div class="container">
        <div class="col-md-12">
          <div class="blog-post  blog-post--fullwidth">
            <div class="blog-post-wrapper">
              <div class="blog-post__info  blog-post__info--top">
                
              </div>
              <div class="blog-post__title">
                <h1>{{data.title}}</h1>
              </div>
              <div class="blog-post__info">
                <span>By <a href="#">Admin</a></span>
                <span>{{data.created_at}}</span>
                <span><a href="#">3 Comments</a></span>
              </div>
            </div>
            <div class="blog-post__image">
              <img src="{% static data.picture %}" alt="{{data.title}}">
              
            </div>
            <div class="blog-post-wrapper">
              <div class="blog-post__content">
                {{data.content|safe}}
              </div>
              
              
              
              <div class="blog-post__related">
                {% for dat in data2 %}
                <div class="blog-post__related-item">
                  <a href="{% url 'polls:post' slug=dat.slug %}">
                    <img style="width:278px;height:186px" src="../static/{{ dat.picture }}" alt="{{dat.title}}">
                    <h6>{{dat.title}}</h6>
                  </a>
                  <span>{{dat.created_at}}</span>
                </div>   
                {%endfor%}  
              </div>           
              
                <div class="blog-post__comments-respond">
                  <h5>Leave a Comment</h5>
                  <div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = "http://127.0.0.1/post/{{data.slug}}";  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = "http://127.0.0.1/post/{{data.slug}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://http-127-0-0-1-8000-post.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>  
            </div>
          </div>
        </div>
      </div>
    </main>
    {% include 'footer.html' %}
    {%endblock%}